# Generated by Django 6.0.7 on 2026-10-01 11:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug (URL)')),
                ('resumen', models.TextField(help_text='Texto breve que aparecerá en la página principal.', max_length=400, verbose_name='Resumen')),
                ('contenido', models.TextField(verbose_name='Contenido completo')),
                ('imagen', models.ImageField(upload_to='eventos/%Y/%m/', verbose_name='Imagen de portada')),
                ('fecha_celebracion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de celebración')),
                ('publicado', models.BooleanField(default=True, verbose_name='Visible al público')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-fecha_celebracion'],
                'indexes': [models.Index(fields=['-fecha_celebracion', 'publicado'], name='eventos_eve_fecha_c_ee0dd2_idx')],
            },
        ),
    ]
