# Generated by Django 6.0.7 on 2026-10-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='plazas',
            field=models.IntegerField(default='30', verbose_name='Plazas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo',
            field=models.CharField(default='Jornadas', help_text='Jornadas, taller, curso', max_length=20, verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
