# Generated by Django 6.0.7 on 2026-10-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_plazas_evento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='plazas',
            field=models.IntegerField(verbose_name='Plazas'),
        ),
    ]
