# Generated by Django 5.0.6 on 2026-06-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("cupcake", "Cupcake"),
                            ("bumblebee", "Bumblebee"),
                            ("corporate", "Corporate"),
                            ("synthwave", "Synthwave"),
                        ],
                        default="light",
                        max_length=50,
                        verbose_name="Tema visual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración del Sitio",
                "verbose_name_plural": "Configuración del Sitio",
            },
        ),
    ]
