# Generated by Django 6.0.6 on 2026-07-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="titulo",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
