# Generated by Django 6.0.6 on 2026-07-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_banner_titulo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banner",
            name="imagen_url",
        ),
        migrations.AddField(
            model_name="banner",
            name="imagen",
            field=models.ImageField(
                default="none",
                upload_to="carrouselPortada/%Y/%m/",
                verbose_name="Imagen del carrousel",
            ),
            preserve_default=False,
        ),
    ]
