# Generated by Django 6.0.7 on 2026-09-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_banner_imagen_url_banner_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('cupcake', 'Cupcake'), ('bumblebee', 'Bumblebee'), ('corporate', 'Corporate'), ('synthwave', 'Synthwave'), ('aqua', 'Aqua'), ('pastel', 'Pastel')], default='light', max_length=50, verbose_name='Tema visual'),
        ),
    ]
