# Generated by Django 6.0.7 on 2026-09-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_siteconfiguration_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='bandasLaterales',
            field=models.CharField(choices=[('onduladas', 'Onduladas'), ('rectas', 'Rectas'), ('no', 'No')], default='onduladas', max_length=15, verbose_name='Bandas laterales'),
        ),
    ]
