# Generated by Django 6.0.7 on 2026-10-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_siteconfiguration_bandaslaterales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='bandasLaterales',
            field=models.CharField(choices=[('onduladas', 'Onduladas'), ('rectas', 'Rectas'), ('no', 'No')], default='rectas', max_length=15, verbose_name='Bandas laterales'),
        ),
    ]
