# Generated by Django 6.0.7 on 2026-10-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_siteconfiguration_bandaslaterales'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='colorTexto',
            field=models.CharField(choices=[('blanco', 'negro')], default='negro', max_length=10, verbose_name='Color texto'),
        ),
    ]
