# Generated by Django 6.0.7 on 2026-10-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_banner_colortexto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='colorTexto',
            field=models.CharField(choices=[('black', 'Negro'), ('white', 'Blanco')], default='negro', max_length=10, verbose_name='Color texto'),
        ),
    ]
