# Generated by Django 6.0.7 on 2026-10-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_banner_colortexto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='colorTexto',
        ),
        migrations.AddField(
            model_name='banner',
            name='colorFondo',
            field=models.CharField(choices=[('light', 'Negro'), ('dark', 'Blanco')], default='dark', max_length=10, verbose_name='Color texto'),
        ),
    ]
