# Generated by Django 6.0.7 on 2026-10-10 16:55

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='contenido',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Contenido completo'),
        ),
    ]
