"""
Django settings for WadoWeb project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Carga las variables del archivo .env en os.environ
load_dotenv(
    dotenv_path=BASE_DIR / ".env",
    override=False,
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

DEBUG = (
    os.environ.get("DJANGO_DEBUG", "False")
    .strip()
    .lower()
    in {"true", "1", "yes", "on"}
)


ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        "DJANGO_ALLOWED_HOSTS",
        "",
    ).split(",")
    if host.strip()
]


CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        "DJANGO_CSRF_TRUSTED_ORIGINS",
        "",
    ).split(",")
    if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "pruebas.apps.PruebasConfig",
    "core.apps.CoreConfig", # La mejor práctica es registrar la clase nombreappConfig de cada app
    "noticias.apps.NoticiasConfig",
    "django_tailwind_cli",
    "theme.apps.ThemeConfig",

]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "WadoWeb.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR/'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages", # Context processor para mensajes de Django
                "core.context_processors.site_theme", # Nuestro context processor personalizado para el tema del sitio
            ],
        },
    },
]

WSGI_APPLICATION = "WadoWeb.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

# 3. LA CLAVE: Dile a Django dónde buscar archivos estáticos globales
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Esto le dice a Django que busque archivos estáticos en la carpeta "static" en la raíz del proyecto
    BASE_DIR / "theme" / "static"  # Para los archivos de tailwind y daisyUI
]

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField" # Tipo de campo por defecto para las claves primarias en los modelos de Django

# (Opcional pero recomendado) Ruta donde se descargará el CLI de Tailwind. 
# Por defecto se guarda en ~/.local/bin/, pero al ser WinPython portable, 
# puedes forzar que se quede dentro del proyecto:
import os

# 1. Apunta directamente al archivo ejecutable, no solo al directorio
TAILWIND_CLI_PATH = BASE_DIR / '.tailwind-cli' / 'tailwindcss-windows-x64-4.3.1.exe'

# 2. Desactiva la descarga automática para evitar peticiones bloqueadas por el firewall
TAILWIND_CLI_AUTOMATIC_DOWNLOAD = False

# 3. Especifica la versión del binario local
TAILWIND_CLI_VERSION = '4.3.1'


# Configuración de django-tailwind-cli
TAILWIND_CLI_SRC_CSS = BASE_DIR / 'theme/static/theme/input.css'
TAILWIND_CLI_DIST_CSS = BASE_DIR / 'theme/static/theme/output.css'

# URL pública que interceptará urls.py
MEDIA_URL = '/media/'

# Ruta absoluta aislada para los uploads
MEDIA_ROOT = BASE_DIR / 'media'